apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: {{ .Values.app.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.app.name }}
          servicePort: {{ .Values.port.external }}
        path: /
  tls:
  - secretName: ssl-cert
    hosts:
    - {{ .Values.app.host }}