apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  ports:
  - port: {{ .Values.port.external }}
    protocol: TCP
    targetPort: {{ .Values.port.internal }}
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP